### PR TITLE
Made it so uncaught exceptions get replaced with insults

### PR DESCRIPTION
**Pull request by jacob-indigo**

### CODE REVIEW

**Comment by jacob-indigo** [comment]
Bump

**Comment by keithfma** [comment]
Coming in cold! Sorry for the long delay on this PR.

Plan is to integrate it, and then do a little work to make the neat exception conversion you implemented here an optional feature.

**Review by keithfma — COMMENTED** [review]
Love the idea. Will merge it and then make a few changes so the behavior is optional (but easy to turn on)

**Comment by jacob-indigo** [comment]
What are you doing?!?!?

**Pull request merged**
